# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: [strikethrough,smart,with_toc_data]
highlighter:         pygments

# Permalinks
permalink:        /posts/:title/

# Setup
title:            ANAND MANI SANKAR
tagline:          "thoughts.toString( )"
description:      'Ramblings and opinionated thoughts on technology.'
url:              http://anandmanisankar.com
baseurl:          '/'
paginate:         3
excerpt_separator: "<br>"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

author:
  name:           'Anand Mani Sankar'
  url:            https://twitter.com/msanand
  twitter:        msanand
  disqus:         thejournalofanandmanisankar
  addthis_pubid:  ra-53e8fec950d56b1c

# Custom vars
version:          1.4.0

github:
  repo:           https://github.com/msanand/msanand.github.io
  feedback:       https://github.com/msanand/feedback/issues/new
