# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     [strikethrough,smart,with_toc_data,tables]
highlighter:      pygments

# Permalinks
permalink:        /posts/:title/

# User Configuration
title:            Capital Engineering
tagline:          'Software'
description:      'Working now. Shoot Us an email! :)'
url:              http://capitalengineering.github.io
baseurl:          '/'
paginate:         5
excerpt_separator: '<br>'
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Author Info
author:
  name:           'Metumaribe and Co.'
  url:            https://capitalengineering.github.io

# Social Integration
social:
  #twitter:        none
  #disqus:         thejournalofanandmanisankar
  #addthis_pubid:  ra-53e8fec950d56b1c

# Google Analytics Configuration
# Proxy response must be in JSON and should have the fields - ga:pagePath, ga:pageview
google_analytics:
  #tracking_id:      UA-53680945-1
  #super_proxy_url:  http://msa-super-proxy.appspot.com/query?id=ahFzfm1zYS1zdXBlci1wcm94eXIVCxIIQXBpUXVlcnkYgICAgICAgAoM&format=json

# Github
github:
  repo:           https://github.com/CapitalEngineering/home
  feedback:       https://github.com/CapitalEngineering/feedback/issues/new

# Version Info
version:          1.0.1

theme: jekyll-theme-cayman
