# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["strikethrough"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            thoughts.toString( )
tagline:          "Anand Mani Sankar's Journal"
description:      'Ramblings and opinionated thoughts on technology.'
url:              http://msanand.github.io
baseurl:          '/'
paginate:         1

author:
  name:           'Anand Mani Sankar'
  url:            https://twitter.com/msanand

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/msanand/msanand.github.io
